# Generated by Django 5.0.2 on 2024-02-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_customuser_email_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
